entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  mail:
    address: ":25"

accessLog:
  filePath: "/var/log/traefik/access.log"


certificatesResolvers:
  myresolver:
    acme:
      email: billydd129@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
