entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  mail:
    address: ":25"

accessLog:
  filePath: "/var/log/traefik/access.log"

metrics: 
  prometheus: {}


certificatesResolvers:
  myresolver:
    acme:
      email: billydd129@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false


experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: "v1.3.5" # To update
